### ISSUE TITLE
No such environment align

### ISSUE THREAD

**Issue by ndthinh02** [djade007/latext#5]
hi, i have a latext string like this " \left[ \begin{align} &amp; x=\frac{\pi }{4}+k\pi \\ &amp; x=\frac{\pi }{12}+k\frac{\pi }{7} \\ \end{align} \right. " but when converting, it says no such environment align, so is there any way to fix it? thank you

**Comment by ss0314** [comment]
Hello,

Use "**aligned**" environment instead of "**align**" environment.

This **latext** package depends on **Flutter_math_fork** library, and the "**align**" environment seems **not supported** in "**flutter_math_fork**" .


Use "**aligned**" environment like this:

``` 
$\begin{aligned}
  (a+b)^2 &= (a+b)(a+b) \\
  &= a(a+b)+b(a+b) \\
  &= a^2+ab+ba+b^2 \\
  &= a^2+2ab+b^2
  \end{aligned}$
```

Output:


![IMG_5648](https://github.com/djade007/latext/assets/98267188/69215a14-12f1-4dbe-90c4-e341d2527c88)

**Comment by greatsam4sure** [comment]
The above code  fail to run  in Flutter 3.16 and Dart 3.2. What can I do to get it working

**Comment by greatsam4sure** [comment]
Finally got it to work by replacing \\ with \cr as shown below
\begin{aligned}
  (a+b)^2 &= (a+b)(a+b) \cr
  &= a(a+b)+b(a+b) \cr
  &= a^2+ab+ba+b^2 \cr
  &= a^2+2ab+b^2
  \end{aligned}$
